### ISSUE TITLE
npx scrypt-cli project my-project

### ISSUE THREAD

**Issue by yusufidimaina9989** [sCrypt-Inc/scrypt-cli#23] opened 2023-02-27 05:37 UTC
I can't create a new project

**Comment by xhliu** [comment] 2023-02-27 05:39
Can you run these and paste your output?
```
npx scrypt-cli system
npx scrypt-cli -v
```

**Comment by zhfnjust** [comment] 2023-02-27 05:43
@yusufidimaina9989

**Comment by yusufidimaina9989** [comment] 2023-02-27 05:54
I get the same error when i run:

npx scrypt-cli system

And

npx scrypt-cli -v

**Comment by yusufidimaina9989** [comment] 2023-02-27 05:57
![Uploading a5{d1ed2e9} (92a3e02a-7603-41af-bb0c-2f5d6c87e98a id=0x7f0a03f7 tag=BaseCommentFragment) …]()

**Comment by yusufidimaina9989** [comment] 2023-02-27 06:03
@zhfnjust 
I get the same error when i run both :

npx scrypt-cli system

and

npx scypt-cli -v

**Comment by yusufidimaina9989** [comment] 2023-02-27 06:05
![20230227_064921.jpg](https://user-images.githubusercontent.com/120538505/221486933-e11aa5e6-8f72-4d1b-a272-d870b66c9f4f.jpg)
![Uploading a5{ada5a6b} (37fc6729-a741-4cde-ae44-6d37d6942e08 id=0x7f0a03f7 tag=BaseCommentFragment) …]()

**Comment by yusufidimaina9989** [comment] 2023-02-27 06:07
Node.js  v18.13.0

**Comment by zhfnjust** [comment] 2023-02-27 06:15
it seems not a `scrypt-cli` issue.

go to your global `node_modules` and see if a `scrypt-cli`  installed.

your global `node_modules`  path is at `C:\User\p\AppData\Roamin\npm\node_modules\`

if `scrypt-cli`  exists , delete it and try `npx scrypt-cli -v` again.


Also, try running `npx create-react-app app` to check if your npx is working

**Comment by yusufidimaina9989** [comment] 2023-02-27 06:30
I checked it there is no scrypt-cli, let just delete everything, just guide me in a simple way on how to install sCrypt CLI tool from the beginning, thanks

**Comment by yusufidimaina9989** [comment] 2023-02-27 06:30
@zhfnjust

**Comment by zhfnjust** [comment] 2023-02-27 06:35
no need to install.

did you check your npx by:

```sh
npx create-react-app app
```

**Comment by yusufidimaina9989** [comment] 2023-02-27 06:47
Yes, i created the app, its working
@zhfnjust

**Comment by zhfnjust** [comment] 2023-02-27 07:01
ok, now try :

```
npx clear-npx-cache
npx scrypt-cli -v
```

**Comment by zhfnjust** [comment] 2023-02-27 08:33
is it ok? @yusufidimaina9989

**Comment by yusufidimaina9989** [comment] 2023-02-28 01:05
![20230228_020427.jpg](https://user-images.githubusercontent.com/120538505/221725478-e4fc5a3b-8a20-4444-9db2-d27c00edc3d0.jpg)

**Comment by zhfnjust** [comment] 2023-02-28 01:08
ok, I try to reproduce it locally.

**Comment by yusufidimaina9989** [comment] 2023-03-05 21:40
![20230305_223433.jpg](https://user-images.githubusercontent.com/120538505/222987411-cd83f5f5-9c6b-4e57-bd42-c6d12e1f9865.jpg)
The scrypt-cli -v  is 0.1.13,

When i run: npx scrypt-cli system,
The npm packages were not found:

scrypt-ts : Not Found
scryptlib : Not Found

**Comment by yusufidimaina9989** [comment] 2023-03-05 21:40
![20230305_223433.jpg](https://user-images.githubusercontent.com/120538505/222987411-cd83f5f5-9c6b-4e57-bd42-c6d12e1f9865.jpg)
The scrypt-cli -v  is 0.1.13,

When i run: npx scrypt-cli system,
The npm packages were not found:

scrypt-ts : Not Found
scryptlib : Not Found
@zhfnjust

**Comment by zhfnjust** [comment] 2023-03-06 01:31
@yusufidimaina9989  can you create project with following CLI:

```sh
npx scrypt-cli project demo
```

**Comment by zhfnjust** [comment] 2023-03-06 01:35
it seams `npx scrypt-cli -v` now works fine.

did you change something。

**Comment by yusufidimaina9989** [comment] 2023-03-06 05:09
Yes, my project was created successfully, and the vesion is 0.1.13
@zhfnjust

**Comment by yusufidimaina9989** [comment] 2023-03-06 05:12
I didn't change anyghing, but when i run 
```
npx scrypt-cli system
```
it shows 
```
scrypt-ts : Not Found
scryptlib : Not Found
```
And even my smart contracts code can't find the module scrypt-ts and scryptlib
@zhfnjust

**Comment by zhfnjust** [comment] 2023-03-07 05:01
@yusufidimaina9989 did you run: npm install before you get system info?
you need to run npm install after project created.

**Comment by yusufidimaina9989** [comment] 2023-03-07 06:01
Ok, let do it now
@zhfnjust

**Comment by zhfnjust** [comment] 2023-03-07 09:06
@yusufidimaina9989 is it ok , if ok , we can close this issue now

**Comment by zhfnjust** [comment] 2023-03-08 03:10
closed due to inactivity

**Closed by zhfnjust** 2023-03-08 03:10 UTC
Labels: bug
